version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: redstone-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: redstone-monitor
    networks:
      - redstone-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: redstone-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/redstone-monitor
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - redstone-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: redstone-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - redstone-network

volumes:
  mongodb_data:

networks:
  redstone-network:
    driver: bridge
